### ISSUE TITLE
Containerize app

### ISSUE THREAD

**Issue by pythoninthegrass** [devansh016/Eventify#11]
Hi @devansh016! Per our [Hacktoberfest Discord chat](https://discord.com/channels/720788516837261322/735506115810426971/1026495393212665866) (user handle `exographicskip`), you said you were open to containerizing the app on [Heroku](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml).

I'd be happy to set this up, test locally, and document for you as a part of the challenge.

**Comment by pythoninthegrass** [comment]
#16 works on my machine 😼

**Comment by pythoninthegrass** [comment]
Thanks for merging my PR @devansh016! If it's not too much trouble, think the `hacktoberfest-accepted` label [needs to be applied](https://hacktoberfest.com/participation/#maintainers) as well.

**Comment by devansh016** [comment]
already added hacktoberfest label, hacktoberfest-accepted label is not mandatory.

**Comment by pythoninthegrass** [comment]
Got it, thanks! Also, was able to ~~get around the merge conflict by installing `nodemon` globally~~:
```bash
npm i -g nodemon
```

**EDIT**
Spoke too soon. Local node server definitely needs `nodemon` installed via `npm i nodemon --save-dev`. Not a blocker, but might wanna add to your original `package.json` in main.
