### ISSUE TITLE
Improve overall UI of Event Cards

### ISSUE THREAD

**Issue by RathoreAbhiii** [devansh016/Eventify#12]
I would like to improve the overall UI of the event cards by applying suitable hover effects wherever applicable in accordance to the aesthetics of the website.

**Comment by RathoreAbhiii** [comment]
Could you please assign me this issue @devansh016? Thanks!

**Comment by RathoreAbhiii** [comment]
Also, could you add Hacktoberfest tag to this issue? Thanks!

**Comment by RathoreAbhiii** [comment]
I am unable to run the app. Facing the following issue : 
![Screenshot-111](https://user-images.githubusercontent.com/91001195/193781824-508f50ca-becb-4cc5-b9ed-f32072a2feac.png)

**Comment by devansh016** [comment]
try to use sudo

**Comment by RathoreAbhiii** [comment]
Yeah, I figured it out. Thanks!

**Comment by RathoreAbhiii** [comment]
I am closing and unassigning this issue as I am facing a lot of errors while trying to change things up. Sorry for the inconvenience caused.
